---
version: "3.9"
networks:
  default:
    external:
      name: Backend
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=p4ssw0rd
      - TZ=Australia/Brisbane
    volumes:
      - /home/container/mariadb:/var/lib/mysql
    restart: unless-stopped
